### ISSUE TITLE
What is the reason for turning `my_getter [@@js.get]` into `myGetter`?

### ISSUE THREAD

**Issue by sagotch** [alainfrisch/gen_js_api#62]
It makes you need to specify `my_getter [@@js.get "my_getter"]`, so why not use original case?

Edit: And I also need to specify the setter.

**Comment by dannywillems** [comment]
The syntax my_getter is more used than myGetter in OCaml. In JavaScript, my_getter`

**Comment by dannywillems** [comment]
The syntax `my_getter` is more used than `myGetter` in OCaml. In JavaScript, `my_getter` is not very common.

**Comment by sagotch** [comment]
It does not sound like a good justification to me, but I see no other reason...

**Comment by alainfrisch** [comment]
See https://github.com/LexiFi/gen_js_api/blob/master/NAMING.md

Without this implicit convention, one would need to write JS names manually more often (since they tend to be of the form MyGetter rather than my_getter).  You can use js.verbatim_names to avoid applying this convention if it gets in your way.

**Comment by sagotch** [comment]
Ok, maybe that most people would prefer to use `my_getter` rather than `myGetter`...

I don't, and I would prefer to write `val myGetter`, staying closer to the original function name, and have also have a `my_getter` form untouched when I use it (this form is used by googlemaps, for instance).

I see no `[@@@js.verbatim_names]` or `[@@@js.verbatim_names.start]` which would be nice for people like me in order to avoid writing the attribute at the end of each module.
